### ISSUE TITLE
[Feature Request]: history for previously used advanced settings

### ISSUE THREAD

**Issue by push-on** [mashb1t/Fooocus#84] opened 2024-10-08 11:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

an option for loading last used settings. a button or saving my settings so that when i reopen this it loads. or an option for saving different loadout or presets for different types of options. 

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment] 2024-10-09 07:32
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1622.
Please keep in mind that Fooocus is not in active development anymore and we only do security releases.

**Closed by mashb1t** 2024-10-09 07:32 UTC
Labels: enhancement, triage
